<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>1.0.1.1</Version>
    <TargetFramework>net10.0</TargetFramework>
    <Description>A 2048 clone. Open with /a48.</Description>
    <PackageProjectUrl>https://github.com/rail2025/Aether48</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <NoWarn>CA1416</NoWarn>
    <AcceptsFeedback>false</AcceptsFeedback> 
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Images\icon.png" />
    <EmbeddedResource Include="Music\bgm1.mp3" />
    <EmbeddedResource Include="Music\bgm2.mp3" />
    <EmbeddedResource Include="Music\bgm3.mp3" />
    <EmbeddedResource Include="Music\bgm5.mp3" />
    <EmbeddedResource Include="Music\bgm6.mp3" />
    <EmbeddedResource Include="Music\bgm4.mp3" />
    <EmbeddedResource Include="icon.png" />
    <EmbeddedResource Include="Images\aether48title.png" />
    <Content Include="repo.json" />
    <EmbeddedResource Include="Sfx\gameover.wav" />
    <EmbeddedResource Include="Sfx\win.wav" />
    <EmbeddedResource Include="Sfx\advance.wav" />
    <EmbeddedResource Include="Sfx\pop.wav" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

</Project>
